version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: dbvparrot
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbvparrot

    ports:
      - "3306:3306"
    volumes:
        -  ~/apps/parrot:/var/lib/mysql


